[INFO] | 2024-02-20 11:14:25 AM | analyzer.ReentrantVulnerableEtherLossUserDefinedAddress | Analysis started at: 2024-02-20 11:14:25 AM
[INFO] | 2024-02-20 11:14:25 AM | analyzer.ReentrantVulnerableEtherLossUserDefinedAddress | Found version: 0.6.12
Traceback (most recent call last):
  File "contractlint.py", line 65, in analyze_contracts
    slither_obj = Slither(contract_path)
  File "/usr/local/lib/python3.8/dist-packages/slither_analyzer-0.6.8-py3.8.egg/slither/slither.py", line 85, in __init__
    self._analyze_contracts()
  File "/usr/local/lib/python3.8/dist-packages/slither_analyzer-0.6.8-py3.8.egg/slither/solc_parsing/slitherSolc.py", line 252, in _analyze_contracts
    self._analyze_third_part(contracts_to_be_analyzed, libraries)
  File "/usr/local/lib/python3.8/dist-packages/slither_analyzer-0.6.8-py3.8.egg/slither/solc_parsing/slitherSolc.py", line 331, in _analyze_third_part
    self._analyze_variables_modifiers_functions(contract)
  File "/usr/local/lib/python3.8/dist-packages/slither_analyzer-0.6.8-py3.8.egg/slither/solc_parsing/slitherSolc.py", line 371, in _analyze_variables_modifiers_functions
    contract.analyze_content_functions()
  File "/usr/local/lib/python3.8/dist-packages/slither_analyzer-0.6.8-py3.8.egg/slither/solc_parsing/declarations/contract.py", line 285, in analyze_content_functions
    function.analyze_content()
  File "/usr/local/lib/python3.8/dist-packages/slither_analyzer-0.6.8-py3.8.egg/slither/solc_parsing/declarations/function.py", line 221, in analyze_content
    node.analyze_expressions(self)
  File "/usr/local/lib/python3.8/dist-packages/slither_analyzer-0.6.8-py3.8.egg/slither/solc_parsing/cfg/node.py", line 31, in analyze_expressions
    expression = parse_expression(self._unparsed_expression, caller_context)
  File "/usr/local/lib/python3.8/dist-packages/slither_analyzer-0.6.8-py3.8.egg/slither/solc_parsing/expressions/expression_parsing.py", line 446, in parse_expression
    right_expression = parse_expression(expression['rightHandSide'], caller_context)
  File "/usr/local/lib/python3.8/dist-packages/slither_analyzer-0.6.8-py3.8.egg/slither/solc_parsing/expressions/expression_parsing.py", line 391, in parse_expression
    return parse_call(expression, caller_context)
  File "/usr/local/lib/python3.8/dist-packages/slither_analyzer-0.6.8-py3.8.egg/slither/solc_parsing/expressions/expression_parsing.py", line 268, in parse_call
    called = parse_expression(expression['expression'], caller_context)
  File "/usr/local/lib/python3.8/dist-packages/slither_analyzer-0.6.8-py3.8.egg/slither/solc_parsing/expressions/expression_parsing.py", line 673, in parse_expression
    raise ParsingError('Expression not parsed %s'%name)
slither.solc_parsing.exceptions.ParsingError: Expression not parsed FunctionCallOptions
[36m[#] Analysing started: ReentrantVulnerableEtherLossUserDefinedAddress.sol[0m
