[INFO] | 2024-02-20 11:07:44 AM | analyzer.ReentrantVulnerableEtherLossUserDefinedAddress | Analysis started at: 2024-02-20 11:07:44 AM
[INFO] | 2024-02-20 11:07:44 AM | analyzer.ReentrantVulnerableEtherLossUserDefinedAddress | Found version: 0.7.6
Traceback (most recent call last):
  File "contractlint.py", line 65, in analyze_contracts
    slither_obj = Slither(contract_path)
  File "/usr/local/lib/python3.8/dist-packages/slither_analyzer-0.6.8-py3.8.egg/slither/slither.py", line 85, in __init__
    self._analyze_contracts()
  File "/usr/local/lib/python3.8/dist-packages/slither_analyzer-0.6.8-py3.8.egg/slither/solc_parsing/slitherSolc.py", line 242, in _analyze_contracts
    self._analyze_first_part(contracts_to_be_analyzed, libraries)
  File "/usr/local/lib/python3.8/dist-packages/slither_analyzer-0.6.8-py3.8.egg/slither/solc_parsing/slitherSolc.py", line 289, in _analyze_first_part
    self._parse_struct_var_modifiers_functions(contract)
  File "/usr/local/lib/python3.8/dist-packages/slither_analyzer-0.6.8-py3.8.egg/slither/solc_parsing/slitherSolc.py", line 344, in _parse_struct_var_modifiers_functions
    contract.parse_state_variables()
  File "/usr/local/lib/python3.8/dist-packages/slither_analyzer-0.6.8-py3.8.egg/slither/solc_parsing/declarations/contract.py", line 231, in parse_state_variables
    var = StateVariableSolc(varNotParsed)
  File "/usr/local/lib/python3.8/dist-packages/slither_analyzer-0.6.8-py3.8.egg/slither/solc_parsing/variables/variable_declaration.py", line 52, in __init__
    self._init_from_declaration(var, var['value'])
KeyError: 'value'
[36m[#] Analysing started: ReentrantVulnerableEtherLossUserDefinedAddress.sol[0m
